CartoDB/airship

- .gitignore
- src/components/Button/__snapshots__/button-group.test.js.snap
- src/components/Button/button-group.js
- src/components/Button/button.js
- src/components/Button/button.stories.js
- src/utils/index.js
- src/utils/is-component-of-type.js
This PR fixes a bug in the `ButtonGroup` component. We were checking the type with `child.type.name === 'Button'` which is minified in the production build, so the conditional is always false, that lead to some styles being wrong. I added a custom function that just compares the type.
> Fix Button type checking in bundled assets

- docs/components/popup.md
- docs/index.js
- package.json
- src/components/Popup/__snapshots__/popup.test.js.snap
- src/components/Popup/popup.js
- src/components/Popup/popup.stories.js
- src/components/Popup/popup.test.js
This PR adds the `<Popup />` component.
- Only image popup doesn't work on IE/Edge
> Add <Popup />

- src/components/Range/range.js
- src/components/Range/range.stories.js
This PR handles the change to `minValue` and `maxValue` by changing the `isWithinRange` method.
> Handle next min/max values on range update

- DEVELOPERS.md
> Add release instructions

- examples/layouts/generic.html
- packages/styles/src/core/layout/_generic.scss
- packages/styles/src/core/layout/_sidebar.scss
- packages/styles/src/core/layout/toolbar/_actions.scss
- packages/styles/src/core/layout/toolbar/_main.scss
- packages/styles/src/core/layout/toolbar/_tabs.scss
- packages/styles/src/core/variables/_sizes.scss
- packages/styles/src/core/variables/_variables.scss
Refactor Toolbar styles to use a simpler HTML markup
> Refactor toolbar styles

- _redirects
- catalog/index.html
- packages/styles/src/tabs/tabs.scss
> Use Netlify for documentation

- packages/styles/src/tabs/tabs.scss
> Fix margin in tabs__item

- catalog/index.html
- packages/styles/src/airship.scss
- packages/styles/src/radio/README.md
- packages/styles/src/radio/_radio.scss
- packages/styles/src/radio/radio.spec.js
- packages/styles/src/radio/test/radio-base.html
- packages/styles/src/radio/test/radio.html
> Radio buttons

- examples/layouts/map-wrapper/map-wrapper-bottom.html
Closes: https://github.com/CartoDB/airship/issues/125
> Use showBottom instead of showBottomPanel

- catalog/index.html
- examples/components/as-category-widget/bar-only.html
- examples/components/as-category-widget/simple.html
- examples/components/as-category-widget/total-percentage.html
- packages/components/package.json
- packages/components/src/components.d.ts
- packages/components/src/components/as-category-widget/README.md
- packages/components/src/components/as-category-widget/__snapshots__/as-category-widget.spec.ts.snap
- packages/components/src/components/as-category-widget/as-category-widget.html
- packages/components/src/components/as-category-widget/as-category-widget.scss
- packages/components/src/components/as-category-widget/as-category-widget.spec.ts
- packages/components/src/components/as-category-widget/as-category-widget.tsx
- packages/components/src/utils/readable-number.ts
- packages/components/src/utils/styles.js
- packages/components/stencil.config.js
- packages/components/tsconfig.json
This PR contains Category Widget as a Web Component. The functionality is described in #90.
Styles and colors were taken from Sketch design.
> Category Widget

- packages/components/src/components/as-category-widget/README.md
- packages/components/src/components/as-category-widget/__snapshots__/as-category-widget.spec.ts.snap
- packages/components/src/components/as-category-widget/as-category-widget.scss
- packages/components/src/components/as-category-widget/as-category-widget.tsx
> Fix variable names in CategoryWidget

- packages/styles/src/loading/README.md
https://github.com/CartoDB/airship/issues/165
---
> Fix typo in large loading modifier class

- examples/components/as-category-widget/bar-only.html
- examples/components/as-category-widget/simple.html
- examples/components/as-category-widget/total-percentage.html
- packages/components/src/components/as-category-widget/README.md
- packages/components/src/components/as-category-widget/__snapshots__/as-category-widget.spec.ts.snap
- packages/components/src/components/as-category-widget/as-category-widget.html
- packages/components/src/components/as-category-widget/as-category-widget.scss
- packages/components/src/components/as-category-widget/as-category-widget.spec.ts
- packages/components/src/components/as-category-widget/as-category-widget.tsx
Closes: https://github.com/CartoDB/airship/issues/192
> Fix small issues in the category widget

- packages/components/src/components/as-range-slider/slider/as-range-slider.scss
> Add default height to range-slider

- packages/components/src/components/as-range-slider/slider/as-range-slider.scss
> Modify slider width

- doc/guides/00-introduction.md
> 212 getting started guide

- packages/styles/src/core/layout/toolbar/README.md
https://github.com/CartoDB/airship/issues/183
> Add mention to .as-toolbar and tell about default toolbar position

- packages/styles/src/tabs/README.md
- packages/styles/src/tabs/tabs.scss
- packages/styles/src/tabs/test/tabs-xl.html
- packages/styles/src/tabs/test/tabs.html
https://github.com/CartoDB/airship/issues/167
> Make tabs scroll horizontally

- packages/styles/src/core/layout/toolbar/_toolbar.scss
> Change anchor color in toolbar to color-ui-01

- packages/icons/package.json
> Add style and main entry points to the icons package

- docs/guides/05-icons.md
> Add icons guide

- docs/guides/03-web-components.md
> Add web components guide

- docs/guides/02-content.md
Content repository guide for Airship Developer Center.
https://github.com/CartoDB/airship/issues/235
> Content guide

- docs/guides/01-css-elements.md
> CSS elements guide

- docs/guides/06-advanced-guide-cartojs.md
> Advanced CARTO.js guide using Airship

- docs/guides/06-advanced-guide-styling.md
https://github.com/CartoDB/airship/issues/242
> Advanced Styling guide

- examples/layouts/sidebar/sidebar.html
- packages/styles/src/core/layout/sidebar/README.md
#236  Update sidebar reference
---
> Update sidebar docs

- docs/guides/00-integration-carto-vl.md
- examples/usage-with-carto-vl.html
> Add carto-vl guide

- packages/styles/src/core/layout/sidebar/_sidebar.scss
> Add sidebar scroll

- packages/components/README.md
> Add README.md to Components package

- packages/styles/package.json
- packages/styles/scripts/rename-css-files.sh
> 270 minify css

- packages/styles/src/core/layout/toolbar/_toolbar.scss
> Fix variable typos

- docs/guides/03-layout.md
> Add basic layout guide

- examples/components/as-category-widget/interaction-disabled.html
- examples/components/as-histogram-widget/interaction-disabled.html
- packages/components/src/components.d.ts
- packages/components/src/components/as-category-widget/README.md
- packages/components/src/components/as-category-widget/as-category-widget.scss
- packages/components/src/components/as-category-widget/as-category-widget.spec.ts
- packages/components/src/components/as-category-widget/as-category-widget.tsx
- packages/components/src/components/as-histogram-widget/README.md
- packages/components/src/components/as-histogram-widget/as-histogram-widget.html
- packages/components/src/components/as-histogram-widget/as-histogram-widget.scss
- packages/components/src/components/as-histogram-widget/as-histogram-widget.tsx
> Disable widgets interactivity

- packages/icons/README.md
> Add icons list

- docs/guides/11-Angular-integration.md
> Angular integration guide

- packages/styles/src/avatar/README.md
- packages/styles/src/badges/README.md
- packages/styles/src/banner/README.md
- packages/styles/src/breadcrumb/README.md
- packages/styles/src/buttons/README.md
- packages/styles/src/checkbox/README.md
- packages/styles/src/core/layout/main/map-area/README.md
- packages/styles/src/core/layout/main/map-area/map-panels/README.md
- packages/styles/src/core/layout/main/map-footer/README.md
- packages/styles/src/core/layout/sidebar/README-CONTAINERS.md
- packages/styles/src/core/lists/README.md
- packages/styles/src/core/typography/README.md
- packages/styles/src/flag/README.md
- packages/styles/src/inputs/README.md
- packages/styles/src/loading/README.md
- packages/styles/src/menu-dropdown/README.md
- packages/styles/src/modal/README.md
- packages/styles/src/radio/README.md
- packages/styles/src/table/README.md
- packages/styles/src/tabs/README.md
- packages/styles/src/tooltip/README.md
- packages/styles/src/utilities/README.md
> Show HTML source in specimens

- docs/guides/07-layout.md
> Fix layout image path

- docs/guides/01-introduction.md
> Add mapbox styles and scripts in basic example

- packages/components/src/components.d.ts
- packages/components/src/components/as-switch/__snapshots__/as-switch.spec.ts.snap
- packages/components/src/components/as-switch/as-switch.html
- packages/components/src/components/as-switch/as-switch.scss
- packages/components/src/components/as-switch/as-switch.spec.ts
- packages/components/src/components/as-switch/as-switch.tsx
> Add built-in label to switch component

- packages/styles/src/core/variables/colors.md
> Add utilities to colors guide

- packages/styles/src/core/layout/_layout.scss
> Fix img styling in toolbar

- packages/components/src/components/as-responsive-content/README.md
> Make as-responsive-content docs great again

- packages/styles/src/core/variables/colors.md
> Add text to utility classes preview in Colors section

- docs/guides/12-Vue-integration.md
> Vue integration guide

- packages/components/src/components/as-switch/README.md
> Add Switch label documentation

- docs/guides/09-integrating-CARTO-VL.md
> Remove TODO comment

- packages/styles/scripts/rename-css-files.sh
> Prevent .min.min.min when releasing a new version

- packages/components/src/components/as-category-widget/README.md
- packages/components/src/components/as-dropdown/README.md
- packages/components/src/components/as-histogram-widget/README.md
- packages/components/src/components/as-range-slider/slider/README.md
- packages/components/src/components/as-responsive-content/README.md
- packages/styles/src/core/layout/README.md
- packages/styles/src/core/layout/main/map-area/map-panels/README.md
- packages/styles/src/core/layout/sidebar/README.md
> 333 add links to examples

- docs/guides/11-integrating-Angular.md
I forgot to put Custom Element definition in our Angular guide 🤦‍♂️
> Add custom element definition to angular guide

- catalog/index.html
> Remove toolbar entry in reference

- docs/guides/10-integrating-react.md
- docs/guides/11-integrating-Angular.md
- docs/guides/12-integrating-Vue.md
- package-lock.json
- packages/components/src/components/as-category-widget/README.md
- packages/components/src/components/as-dropdown/README.md
- packages/components/src/components/as-histogram-widget/README.md
- packages/components/src/components/as-responsive-content/README.md
Update documentation accordingly to #406 and StencilJS breaking changes.
> Update documentation to reflect @Method changes in Stencil 0.13

- catalog/index.html
Fix https://github.com/CartoDB/developers/issues/446 with https://github.com/CartoDB/developers/pull/449
> Post airship-docs message

- docs/guides/02-getting-started.md
- docs/guides/10-integrating-react.md
- docs/guides/11-integrating-Angular.md
- docs/guides/12-integrating-Vue.md
- examples/usage-from-webpack-components/index.js
> Update guides to reflect new defineCustomElements

- DEVELOPERS.md
> Update developers.md with cc guide

- packages/components/src/components.d.ts
- packages/components/src/components/as-dropdown/as-dropdown.html
- packages/components/src/components/as-dropdown/as-dropdown.spec.ts
- packages/components/src/components/as-dropdown/as-dropdown.tsx
- packages/components/src/components/as-dropdown/types/DropdownOption.d.ts
Better than leaving 1000 comments in the CR  :)
> CR suggestions

- catalog/index.html
- examples/components/as-tabs/simple.html
- packages/components/src/components.d.ts
- packages/components/src/components/as-tabs/README.md
- packages/components/src/components/as-tabs/as-tabs.e2e.ts
- packages/components/src/components/as-tabs/as-tabs.html
- packages/components/src/components/as-tabs/as-tabs.scss
- packages/components/src/components/as-tabs/as-tabs.tsx
> Add airship tabs

- packages/components/src/components/as-histogram-widget/as-histogram-widget.scss
- packages/components/src/components/as-histogram-widget/as-histogram-widget.tsx
- packages/components/src/components/as-histogram-widget/responsive.html
- packages/components/src/components/as-histogram-widget/types/Container.d.ts
- packages/components/src/components/as-histogram-widget/utils/draw.service.ts
- packages/components/src/components/as-stacked-bar-widget/as-stacked-bar-widget.tsx
> Responsive histogram

- packages/components/src/components/as-tabs/as-tabs.tsx
> Fix wrong selector

- packages/components/src/components/as-histogram-widget/as-histogram-widget.tsx
> Fix histogram colors on IE11

- packages/smoke/cdn/smoke_0.html
- packages/smoke/current/smoke_0.html
- packages/styles/src/core/layout/main/map-footer/_map-footer.scss
- packages/styles/src/core/layout/sidebar/_sidebar.scss
Fix smoke issue found in `beta.10`
Use display instead opacity to show/hide tabs
> Fix responsive content

- packages/styles/src/core/layout/toolbar/_actions.scss
> Toolbar actions menu behind sidebar panels on responsive

- packages/components/src/components/as-stacked-bar-widget/as-stacked-bar-widget.tsx
> fix(components): Prevent stacked-bar errors when widget is not visible

- packages/components/src/components/as-histogram-widget/as-histogram-widget.scss
- packages/components/src/components/as-histogram-widget/as-histogram-widget.tsx
> Several Histogram Fixes

- packages/components/src/components.d.ts
- packages/components/src/components/as-responsive-content/as-responsive-content.e2e.ts
- packages/components/src/components/as-responsive-content/as-responsive-content.html
- packages/components/src/components/as-responsive-content/as-responsive-content.tsx
- packages/components/src/components/as-responsive-content/utils/ApplicationSection.ts
- packages/components/src/components/as-responsive-content/utils/content.service.ts
- packages/smoke/current/smoke_0.html
- packages/smoke/index.html
- packages/styles/src/core/layout/main/map-area/map-panels/_map-panels.scss
> Refactor as-responsive-content

- packages/components/src/components/as-category-widget/as-category-widget.scss
- packages/smoke/cdn/smoke_0.html
- packages/smoke/current/smoke_0.html
Fix #532 
---
Updates also the `current` and `cdn` smoke tests with a category widget in the sidebar.
> Fit category widget width to default sidebar

- docs/support/04-browser-support.md
Fixes https://github.com/CartoDB/developers/issues/478
> Fix md doc browser support

- catalog/index.html
> Fix Time Series Widget title

- packages/bridge/src/vl/time-series/TimeSeries.spec.ts
Fix the bridge specs, because Typescript
> Fix bridge specs

- examples/bridge/category/category.html
- examples/bridge/histogram/simple.html
- examples/bridge/time-series/simple.html
Fix #581
---
I have updated the bridge examples to remove the space in line 1 (#581) and also to change the spacing.
NOTE: style tests are broken in `master`
> 581 fix examples spacing

- .circleci/config.yml
- examples/usage-from-sass/package.json
- examples/usage-from-webpack/package.json
- package-lock.json
- packages/components/package.json
- packages/components/src/components.d.ts
- packages/components/src/components/as-histogram-widget/as-histogram-widget.tsx
- packages/components/src/components/as-histogram-widget/utils/interaction.service.ts
- packages/components/stencil.config.js
- packages/smoke/npm/package.json
- packages/styles/package.json
Fix #592 
---
I had to add an extra parameter to force the emitting of the event in some particular cases (like this one). I'm going to keep it undocumented because I don't think there'll be a real use for now.
> Emit selectionChanged when clicking on bucket

- packages/bridge/src/vl/legends/index.ts
Fix https://github.com/CartoDB/airship/issues/604
---
Related CARTOframes PR https://github.com/CartoDB/cartoframes/pull/699
> Customize others label

- packages/components/src/components/legends/as-bubble-legend/as-bubble-legend.html
- packages/components/src/components/legends/as-color-steps-legend/as-color-steps-legend.html
- packages/components/src/components/legends/as-legends/as-legends.scss
- packages/components/src/components/legends/as-legends/as-legends.tsx
- packages/components/src/components/legends/as-point-size-legend/as-point-size-legend.html
- packages/components/src/components/legends/width-ramp-legend.html
> 608 legend fix

- packages/components/src/components/as-histogram-widget/as-histogram-widget.tsx
> Rounding the selection to avoid errors

- .circleci/config.yml
- CHANGELOG.md
- examples/usage-from-sass/package.json
- examples/usage-from-webpack/package.json
- lerna.json
- packages/bridge/CHANGELOG.md
- packages/bridge/package.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/components/src/components.d.ts
- packages/components/src/components/as-histogram-widget/as-histogram-widget.tsx
- packages/components/src/components/as-histogram-widget/utils/interaction.service.ts
- packages/components/src/components/as-responsive-content/as-responsive-content.tsx
- packages/components/stencil.config.js
- packages/icons/CHANGELOG.md
- packages/icons/package.json
- packages/smoke/npm/package.json
- packages/styles/CHANGELOG.md
- packages/styles/package.json
No plans to add more patches to 2.0 since we're about to release 2.1.0, we have to incorporate the changes we did to master.
After this release we'll reconsider the branching strategy and try to use a similar one to CARTO VL
> Merge 2.0.x into master

- catalog/index.html
- examples/bridge/legends/multi-layer-legends.html
- examples/bridge/legends/ramp-legends.html
- examples/components/legends/as-legend-basic.html
- examples/components/legends/as-legend-category.html
- examples/components/legends/as-legend-color-bins-polygon.html
- examples/components/legends/as-legend-color-continuous-polygon.html
- examples/components/legends/as-legend-size-bins-line.html
- examples/components/legends/as-legend-size-bins-point.html
- examples/components/legends/as-legend-size-category-line.html
- examples/components/legends/as-legend-size-continuous-line.html
- examples/components/legends/as-legend-size-continuous-point-scaled.html
- examples/components/legends/as-legend-size-continuous-point.html
- examples/components/legends/orientation.html
- examples/examples.json
- package.json
- packages/bridge/src/vl/legends/README.md
- packages/components/src/components.d.ts
- packages/components/src/components/legends/README.md
> Legends docs + examples

- packages/components/src/components/as-infowindow/README.md
Fix CSS variables documentation issue
> Fix infowindow documentation for CSS variables

- package-lock.json
- packages/bridge/package.json
- packages/bridge/src/vl/VLBridge.ts
- packages/bridge/src/vl/animation-controls/AnimationControls.ts
- packages/bridge/src/vl/base/BaseFilter.ts
- packages/bridge/src/vl/time-series/TimeSeries.ts
- packages/components/package.json
Airship VL Bridge: Restart animation when a filter is applied
Fix https://github.com/CartoDB/cartoframes/issues/1359
---
> fix: Airship VL Bridge: Restart animation when a filter is applied

- packages/bridge/src/vl/time-series/TimeSeries.spec.ts
> Fix mitt in specs

- packages/components/src/components/as-category-widget/as-category-widget.tsx
Fix ch58614
---
Render null values as empty in category widget
> Fix rendering null values as 0 in category widget

- package-lock.json
feat: Allow multi-selection in category widget
fix: Fix histogram showing incorrect numeric values on axis
fix: Improve legend values formatting call
> v2.3.2 release

- packages/components/src/components/as-histogram-widget/as-histogram-widget.e2e.ts
- packages/components/src/components/as-histogram-widget/utils/draw.service.ts
> fix: remove SI format and set new rules to format X axis for histogram [ch76214]

- packages/components/src/components/as-histogram-widget/as-histogram-widget.e2e.ts
- packages/components/src/components/as-histogram-widget/utils/draw.service.ts
> fix: Return to SI format for values using precision higher than 3 and values higher than 999

- CHANGELOG.md
- lerna.json
- packages/bridge/CHANGELOG.md
- packages/bridge/package-lock.json
- packages/bridge/package.json
- packages/components/CHANGELOG.md
- packages/components/package-lock.json
- packages/components/package.json
- packages/icons/CHANGELOG.md
- packages/icons/package-lock.json
- packages/icons/package.json
- packages/styles/CHANGELOG.md
- packages/styles/package-lock.json
- packages/styles/package.json
> Release v2.4.0
