src/components/Checkbox/__snapshots__/checkbox.test.js.snap, src/components/Checkbox/checkbox.js, src/components/Checkbox/checkbox.stories.js
In https://github.com/CartoDB/airship/pull/9 we removed the `reset.css` which broke the checkbox component since it was using the `box-sizing` property from it.
This PR adds the `box-sizing` to the checkbox to fix it.
=> Add box-sizing to checkbox

docs/components/checkbox.md, src/components/Checkbox/__snapshots__/checkbox.test.js.snap, src/components/Checkbox/checkbox.js, src/components/Checkbox/checkbox.stories.js, src/components/Checkbox/checkbox.test.js
We were using `classNames` under a styled component wrapper, this PR moves every element into it's own styled component.
=> Migrate checkbox to styled-components

CHANGELOG.md, docs/components/collapsible.md, src/components/Collapsible/__snapshots__/collapsible.test.js.snap, src/components/Collapsible/collapsible.js, src/components/Collapsible/collapsible.stories.js, src/components/Collapsible/collapsible.test.js, src/utils/getObjectValue.js, src/utils/index.js, src/utils/withOverride.js
This PR adds an `overrides` prop to the `<Collapsible />` component to be able to override styles.
Example:
```
const overrides = {
Collapsible: `
background: #CCC;
width: 400px;
`,
'Collapsible.Header': `
background: #AAA;
padding: 1rem;
`,
'Collapsible.Content': `
padding: 1rem;
`,
};
return (
<Collapsible overrides={overrides}>
<Collapsible.Header>Header</Collapsible.Header>
<Collapsible.Content>Content</Collapsible.Content>
</Collapsible>
)
```
=> Add overrides to <Collapsible />

package.json, packages/components/package.json, packages/components/src/components/as-switch/as-switch.spec.ts, packages/components/src/components/as-switch/as-switch.tsx
Related to https://github.com/CartoDB/airship/issues/51
This PR sets up component testing with Jest. It was already configured in Stencil, but as we use multiple packages I needed to change the path of a file.
There are two new npm scripts:
- `test:components`: which launches Web Component tests only, and check them once.
- `test:components:watch`: which launches Web Component tests only, but it passes the test suite every time a file is modified. There's a mini GUI with multiple options, but by default, it only runs the tests compelling to the files which its code has been modified since last commmit.
=> Web Components testing

README.md
#172
We're linking on the repo description to the website, where there's a lin to catalog, but this adds it to the README as well.
=> Add link to documentation on the README

packages/components/package.json, packages/components/src/components/as-histogram-widget/__snapshots__/as-histogram-widget.spec.ts.snap, packages/components/src/components/as-histogram-widget/as-histogram-widget.html, packages/components/src/components/as-histogram-widget/as-histogram-widget.scss, packages/components/src/components/as-histogram-widget/as-histogram-widget.tsx, packages/styles/src/buttons/buttons.scss
#205
---
I fixed two problems, the selector overflowed a few pixels on the right, so I made it visible, and I've added d3-format as an explicit dependency to fine tune the axis format.
The `0k` was driving me insane :upside_down_face:, it seems like d3-axis has some issues when specifying a string format instead of the d3-format function.
=> Fix some histogram issues

examples/layouts/common/tabs.js, packages/components/src/components/as-application-content/as-application-content.spec.ts, packages/components/src/components/as-application-content/as-application-content.tsx, packages/components/src/components/as-toolbar/as-toolbar.tsx, packages/styles/src/core/containers/test/containers-in-sidebar-bottom-and-legends.html, packages/styles/src/core/containers/test/containers-in-sidebar.html, packages/styles/src/core/layout/sidebar/README.md, packages/styles/src/core/layout/sidebar/_sidebar.scss, packages/styles/src/core/layout/sidebar/test/sidebar-mobile-visible.html
We were not respecting sidebar classes to position elements, so this PR fixes that bug. And I made some modifications to sidebar visible classes because they were not BEM compliant.
https://github.com/CartoDB/airship/issues/202
=> Allow sidebars to be in a different DOM order while maintaining position

packages/components/src/components/as-application-content/README.md
JS code that depends on layout needs to be executed after `load` event is fired and it wasn't mentioned on documentation. So, this PR fixes that.
Related to https://github.com/CartoDB/airship/issues/182.
=> JS code inside load event in <as-application-content>

packages/components/src/components/as-range-slider/thumb/as-range-slider-thumb.scss
@piensaenpixel told us that the text below the thumb should not move, so I removed the translate property.
https://github.com/CartoDB/airship/issues/171
=> Remove thumb text translation

packages/components/src/components/as-category-widget/as-category-widget.spec.ts, packages/components/src/components/as-category-widget/as-category-widget.tsx
I discovered that we were always taking into account Other category value to calculate total percentage sum to render category bars. This PR solves this by excluding that category from sum.
=> Do not take Other category into account in total percentage sum

catalog/index.html, examples/styles/tabs/tabs-accesible.html, examples/styles/tabs/tabs-xl.html, examples/styles/tabs/tabs.html, packages/styles/src/tabs/README.md
Netlify docs are now broken because some changes due to DC integration. `intro` page is not working.
Apart from that, tab code has been copied from their `test` folder to `examples` for Catalog to be able to access it in DC.
=> Fix Netlify documentation

packages/components/src/components/as-histogram-widget/as-histogram-widget.tsx
This issue fixes #289.
The jumpy behaviour was caused because we were setting the range start to the next bucket instead of the same one that was previously selected when new data was set.
=> Adjust selection to bucket start when data changes

packages/components/src/components/as-range-slider/slider/as-range-slider.tsx, packages/components/src/components/as-range-slider/thumb/as-range-slider-thumb.tsx, packages/components/src/utils/get-decimal-places.ts
This PR fix #315 and fix #312.
Range slider thumb position was being calculated with rail's offsetLeft, and it was not calculated properly when any of the parent elements had any `position: relative`, like `.as-main`. So, this PR uses left offset from `.getBoundingClientRect` which is relative to `document` origin.
Apart from that, we didn't allow decimal numbers in slider's step, and now we do! 🎉
=> Fix Range Slider bugs

packages/components/src/components/as-histogram-widget/__snapshots__/as-histogram-widget.spec.ts.snap, packages/components/src/components/as-histogram-widget/as-histogram-widget.scss, packages/components/src/components/as-histogram-widget/as-histogram-widget.tsx
Fix #320.
I fixed SVG height issues, but we need to add a note to documentation telling that if you use that widget in a panel you should put a fixed width by default. Otherwise it would render wrongly because its initial width will be 0.
=> Adjust SVG inner elements to bounds

packages/components/src/components/as-range-slider/MouseTrack.ts, packages/components/src/components/as-range-slider/track/as-range-slider-bar.spec.ts, packages/components/src/components/as-range-slider/track/as-range-slider-bar.tsx
Fix #346.
The `touchstart` and `touchend` event listeners were not being properly removed, hence we were moving all thumbs 🤦‍♂️ .
I updated slider event to make it work in mobile. We were not getting touch event position properly.
=> Remove listeners for Touch events in Range Slider

packages/components/src/components/as-category-widget/README.md, packages/components/src/components/as-category-widget/as-category-widget.scss, packages/components/src/components/as-dropdown/README.md, packages/components/src/components/as-histogram-widget/README.md, packages/components/src/components/as-histogram-widget/as-histogram-widget.scss, packages/styles/src/core/layout/main/map-footer/README.md, packages/styles/src/core/layout/sidebar/README.md, packages/styles/src/core/layout/toolbar/README.md
By default, Markdown parser in catalog converts `--` to `―`, making it difficult to understand CSS variables or CSS classes characters.
Fixes #349.
=> Escape double dashes in Markdown

docs/guides/05-web-components.md, docs/guides/09-integrating-CARTO-VL.md, docs/guides/10-integrating-react.md, docs/guides/11-integrating-Angular.md, docs/guides/12-integrating-Vue.md
I saw that some of the paragraph titles on the guides were very big, so here's the fix. Please add some other wrong paragraphs that you see.
=> Set proper format for guide paragraphs

packages/components/src/components/as-range-slider/thumb/as-range-slider-thumb.tsx, packages/components/src/components/as-range-slider/track/as-range-slider-bar.tsx
We introduced a check of `TouchEvent` variable to distinguish between Desktop and Mobile events. Seems like that `TouchEvent` variable is not defined in Safari, leading to errors when dragging Range Slider's thumb.
=> Avoid checking TouchEvent to fix Range Slider in Safari

catalog/index.html
This PR fixes `inception` in dev center. Where a click on an absolute link only changes the iframe contents.
It listen on any click on anchor tags, see if it's not a hash URL and send the message to the iframe listener.
The listener is on the `developers` PR https://github.com/CartoDB/developers/pull/445
=> Fix Inception in dev reference

packages/components/src/components/as-category-widget/as-category-widget.e2e.ts, packages/components/src/components/as-category-widget/as-category-widget.tsx
This PR reverts #332 until we find a better way to handle the behaviour it tried to fix.
With that PR, any change on categories resets the selection. In CARTO.js that's the normal way of operating, changing the categories of the widget when the source changes, but the selection still makes sense. Now it's impossible to filter via widget.
=> Revert #332

scripts/release-s3.js
#418
---
This also fixes the broken encoded characters on the banner on top of some css and js files.
Here's a release (only on s3) to test this out:
```html
<link rel="stylesheet" href="https://libs.cartocdn.com/airship-icons/testing-broken-beta/icons.css">
<link rel="stylesheet" href="https://libs.cartocdn.com/airship-style/testing-broken-beta/airship.css">
<script src="https://libs.cartocdn.com/airship-components/testing-broken-beta/airship.js"></script>
```
=> Add encoding to content-type to avoid issues

packages/components/src/components/as-range-slider/slider/as-range-slider.scss
While using the `<as-range-slider>` component, I ran into the issue of not having the back rail bar visible. This is because the back rail bar has a z-index level of -1. I **think** it is not necessary. When using `z-index: -1`, it is set backwards by default, and therefore, it is not visible.
Example:
=> Change z-index to 0

package.json, packages/components/stencil.config.js
This PR fixes the latest broken builds.
I haven't moved the uploaded folder from `www/build` to `dist` until we have a response from Ionic about the best way to do it.
=> Change publish script

packages/components/src/components/as-range-slider/slider/as-range-slider.spec.ts, packages/components/src/components/as-range-slider/slider/as-range-slider.tsx
Fix #429
---
It was working properly for keyboard events and moving the bar, but not for moving the thumb.
=> Use steps when moving the range slider thumb

packages/components/src/components/as-histogram-widget/as-histogram-widget.scss, packages/components/src/components/as-histogram-widget/as-histogram-widget.tsx, packages/styles/src/inputs/inputs.scss
Fix #479 
---
Apparently IE11 doesn't like CSS + SVG very well :(
I checked Builder and we're also not setting width / height / transform on CSS.
I've also removed a typo in the CSS, it might be the reason why the docs are broken
=> IE11 histogram handles

index.html, packages/components/src/components/as-stacked-bar-widget/utils/data.service.ts, packages/components/src/utils/readable-number.ts
Fix #478 
---
This adds two polyfills we need (String.padStart, and String.repeat for String.padStart), and removes a call to Array.from.
I don't know if Array.from supports calls with a Set, but I checked and Stencil's polyfill always returns an empty array. The one on MDN as well, so I'm guessing no? So I replaced it with a forEach 🤷‍♂️
=> IE11 Stacked Bar

packages/smoke/cdn/smoke_0.html, packages/smoke/current/smoke_0.html, packages/smoke/npm/smoke_0.html, packages/styles/src/core/layout/main/map-area/map-panels/_map-panels.scss, packages/styles/src/core/layout/main/map-footer/_map-footer.scss, packages/styles/src/core/layout/sidebar/_sidebar.scss, packages/styles/src/core/layout/toolbar/_actions.scss
Fixes IE11 sidebar problems from #489
The problem was that `initial` is a value not understood by IE11 at all. I've substituted the ones that caused the problems for their actual value.
There's also a refactor on smoke templates:
- Map area has a background color to check what it's rendering in a given time.
- There's a nav bar with toolbar actions to check the burguer menu.
- Widget feeding is done after `as-responsive-content` `ready` event.
PS: the name of the branch is not well named.
=> Fix IE11 sidebar problems

docs/guides/04-styles.md, docs/guides/05-web-components.md, docs/guides/08-Styling.md, docs/support/04-browser-support.md
After talking with @rochoa (and getting his approval) we're not going to support IE11 in Airship. CARTO VL doesn't support it either and these two libraries must walk together.
Moreover, the experience of Airship in IE11 is half-baked:
- We need to provide extra polyfills only for it.
- We had to write hacks to render well because of the lack of CSS variables support.
- The overall experience doesn't feel as polished. Flexbox nuances, for instance, make some element combinations to be ugly.
- And more... a lot of effort to get a non good experience.
This PR only modifies the docs. I'll open another one to get rid of the IE11 hacks we've done so far.
=> Drop IE11 support

packages/components/src/components/as-stacked-bar-widget/as-stacked-bar-widget.tsx
No issue associated, stacked bar widgets were broken on master.
=> Rename Stacked Bar render guard

package.json, packages/components/src/components/as-histogram-widget/as-histogram-widget.scss, packages/components/src/components/as-histogram-widget/as-histogram-widget.tsx, packages/components/src/components/as-histogram-widget/utils/data.service.ts, packages/components/src/components/as-histogram-widget/utils/draw.service.ts, packages/smoke/current/smoke_0.html
Fix #496 
---
The real reason why this happens is a Math.round, but it also solves a very annoying case where moving the whole selection could potentially shrink or grow when reaching the start or the end of the histogram.
I've changed it so an internal scale is used that always goes from 0 to # of bins, and is converted back for the event fired.
=> Fix histogram for floating values

packages/components/src/components/as-histogram-widget/as-histogram-widget.tsx, packages/components/src/components/as-histogram-widget/utils/draw.service.ts, packages/components/src/components/as-stacked-bar-widget/as-stacked-bar-widget.tsx
Fix #519 
---
This PR makes the bars separation a bit smarter. As the code is right now, if you have enough bars and not enough space, the stacked bar might even crash due to negative bar size.
Now, if the projected bar width falls under a certain threshold (3px because why not), the separation between bars is set to 0.
The result is this:
Same for the histogram, though it's less likely because the bar separation is 1 instead of 4.
/cc @AbelVm
=> Make space between bars adapt to available space

packages/styles/package.json
`npm run dev` in styles package fails in an installation from scratch.
This PR uses `node-sass` in `dev` mode. We are using it in build mode.
=> Use node-sass in watch mode for styles

packages/components/src/components/as-histogram-widget/as-histogram-widget.tsx
Related #525 
---
We should never fire selectionChanged events if we're repainting (and thus, updating the handles) because of a data change.
Also fixed a regression introduced on a recent merge with the selection bars.
=> Don't fire selectionChanged event when data just updated

packages/components/src/components/as-range-slider/slider/as-range-slider.tsx, packages/components/src/components/as-range-slider/thumb/as-range-slider-thumb.tsx
This PR sets min or max value when mouse is past range slider bounds.
There were some cases when sliding mouse so fast to the left didn't fire some `mousemove` events that are necessary to set slider thumb to the left most position. It should happen with the right one as well.
=> Set min value or max value when mouse is past edge bounds

packages/bridge/examples/range.html, packages/bridge/src/types.d.ts, packages/bridge/src/vl/VLBridge.ts, packages/bridge/src/vl/range/GlobalRangeFilter.ts, packages/bridge/src/vl/range/README.md
This PR adds a `global` range slider filter to the Bridge. This lets you easily filter a range for number columns using an as-range-slider widget. Underneath it uses globalMax and globalMin, and a `$x > y and $x < z` filter
I mentioned this in passing to @makella @elenatorro and @jorgesancha while demoing the bridge and thought, hey, might as well add it since it's a low hanging fruit.
=> Range slider filter for VL Bridge

docs/guides/02-getting-started.md
Fix https://github.com/CartoDB/airship/issues/552
=> Include missing mapbox & CARTO VL references in basic template

docs/guides/01-introduction.md
Fix https://github.com/CartoDB/airship/issues/551
---
Update mapbox version used in the guide, removing our old fork, now that we support the official mapbox version (from v0.52).
=> Fix introduction guide

examples/examples.json
Fix for the dev center, the theme examples does not render correctly because of parenthesis.
=> Broken theme example on dev center

packages/components/src/components/as-responsive-content/as-responsive-content.tsx
Ever since Airship v1 this has happened and we only recently noticed.
In order to re-render some widgets that need a parent with actual size, like the histogram or the stacked bar widget, the as-responsive-content widget looks for `as-*` elements each time you switch tabs and calls `forceUpdate`, a stencil method to force a full redraw of the element.
If this method is called too early, the stencil lazy loader has not downloaded the actual element script yet, causing it to fail. 
We noticed that widgets on the panels, _and only on the panels_ were sometimes not rendering. This happens because we set the first element (in tab order) to active, which is where we're doing the force update. Panels are inside of the map element, despite ending on a different tab, so the query locates them too. …
=> Fix as-responsive-content not loading widgets on panels

packages/bridge/src/vl/legends/index.ts
Fix https://github.com/CartoDB/carto-vl/issues/1353
---
Use getLegendData for opacity, which is used in CARTOFrames helpers
=> Use getLegendData for opacity

packages/bridge/src/vl/VLBridge.ts, packages/bridge/src/vl/histogram/NumericalHistogramFilter.ts
In CARTOframes, it is not possible to select the highest value in a Histogram cause the Numerical Histogram Filter was not including it:
This PR also includes a minor fix to check if an animation exists before it tries to restart it.
=> Fix: unable to select highest value in a dataset [ch58611]

packages/bridge/src/vl/legends/index.ts
This PR added the `sort` option in `config` legends to enable CARTO VL sorting config. To be used along with https://github.com/CartoDB/carto-vl/pull/1429
=> Feature: Add option to sort legends in descending order [ch58612]

packages/components/src/components/as-histogram-widget/as-histogram-widget.e2e.ts, packages/components/src/components/as-histogram-widget/utils/draw.service.ts
Fix https://app.clubhouse.io/cartoteam/story/59951/histogram-shows-incorrect-numeric-values
---
=> Improve conditional number format for histograms [ch59951]

packages/styles/src/core/layout/main/map-area/_map-area.scss
This PR adds `overflow: hidden` to map container so that any element that overflows doesn't cause the page to scroll.
=> Add overflow hidden to #map
